# Generated by Django 2.2.10 on 2022-01-10 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('end_time', models.DateTimeField()),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('txt', 'Ответ текстом'), ('one', 'Ответ с одним вариантом'), ('few', 'Ответ с несколькими вариантами')], max_length=3)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test_app.Polls')),
            ],
        ),
    ]
