# Generated by Django 2.2.10 on 2022-01-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20220110_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls',
            old_name='poll_name',
            new_name='name',
        ),
    ]
