# Generated by Django 2.2.10 on 2022-01-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20220110_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='polls',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together={('poll',)},
        ),
    ]
