# Generated by Django 2.2.10 on 2022-01-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20220110_2135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set(),
        ),
    ]
