# Generated by Django 2.2.10 on 2022-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20220112_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
